sudo: required
language: java

jdk:
  - oraclejdk8

after_success:
  - bash .travis_after_success.sh

cache:
  directories:
    - $HOME/.m2

# Use updated jdk version instead of buggy default
addons:
  apt:
    packages:
      - oracle-java8-installer