

jdbc:
  driverClassName: com.mysql.jdbc.Driver
  url: jdbc:mysql://127.0.0.1:3306/opensource?useUnicode=true&characterEncoding=UTF-8
  username: root
  password:

logging:
  level:
    ROOT: INFO
    org.springframework.web: DEBUG
    com.asterisk.opensource.mapper: DEBUG

spring:
  redis:
    host: localhost
    port: 6379
    pool:
      max-active: 50
      max-wait: -1
      max-idle: 20
      min-idle: 0
    timeout: 0
  data:
    elasticsearch:
      cluster-nodes: 127.0.0.1:9300,127.0.0.1:9301
      cluster-name:
      properties:
        client.transport.ignore_cluster_name: true
  kafka:
    producer:
      batch-size: 20



